# Configuration for the fortran :

# Compiler names:
  F90 = mpiifort 

# Setting the path for the netcdf libraries:  
  MYLIB  = /opt/local/lib
  MYINC  = /opt/local/include
  
  NETINC = ${SARA_NETCDF_INCLUDE}
  NETCDF = ${SARA_NETCDF_LIB}
  
  F90FLAGS = -pg -O3 -no-prec-div -I$(MYINC) -I${NETINC} -module $(MOD_PATH)
  LDFLAGS = -L$(MYLIB) -lz -lnetcdff -lnetcdf -lblas -llapack -lpthread